defaults:
  - _self_
  - logger: filesystemlogger
  - override hydra/job_logging: file
  - override hydra/launcher: submitit_local
  
hydra:
  run:
    dir: outputs/${env.name}/${algorithm.name}/${random:4}
  launcher:
    timeout_min: 2880
    cpus_per_task: 1
    mem_gb: 4

seed: null

algorithm:
  total_steps: 8_000 # 100_000
  log_interval: 10_000
  save_interval: 10_000
  eval_interval: 10_000
  eval_episodes: 5
  video_interval: False
  video_frames: 500

env:
  _target_: ..\..\..\..\MARL_codebase.utils.envs.make_env
  name : Soccer-v0
  time_limit : 25
  clear_info: True
  observe_id: False
  wrappers :
    - FlattenActionWrapper
    - FromDictObservationToImageWrapper
    

not_used_wrappers:
  - SquashDones
  - RecordEpisodeStatistics
  - aec_to_parallel
  
  
