total_steps: 1000000
log_interval: 100000
save_interval: 100000
eval_interval: 100000
eval_episodes: 10
video_interval: 100000
video_frames: 500
name: dqn
model:
  _target_: MARL_codebase.algorithms.dqn.model.QNetwork
  layers:
  - 128
  - 128
  - 128
  parameter_sharing: false
  use_orthogonal_init: true
  device: cuda
training_start: 2000
buffer_size: 75000
optimizer: Adam
lr: 0.0006
gamma: 0.99
batch_size: 128
grad_clip: false
use_proper_termination: true
standardize_returns: true
eps_decay_style: linear
eps_start: 1.0
eps_end: 0.05
eps_decay: 6.5
greedy_epsilon: 0.05
target_update_interval_or_tau: 200
